services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mlflow

  scheduler:
    build:
      context: .
      dockerfile: dockerfile.scheduler
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:  
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
        - mlflow_data:/mlruns

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
        - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  mlflow_data:
  prometheus_data:
  grafana_data: