services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    volumes:
      - ./backend/modules/data:/app/backend/modules/data

  scheduler:
    build:
      context: .
      dockerfile: dockerfile.scheduler
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    volumes:
      - ./backend/modules/data:/app/backend/modules/data
      
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
      
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --allowed-hosts "mlflow:5000,localhost:5000,127.0.0.1:5000,localhost:5050,127.0.0.1:5050"
    ports:
      - "5050:5000"
    volumes:
      - mlflow_data:/mlflow
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',5000)); s.close()"
        ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
    - .env

    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_USER: "${EMAIL_ADDRESS}"  
      GF_SMTP_PASSWORD: "${EMAIL_PASSWORD}"  
      GF_SMTP_FROM_ADDRESS: "${EMAIL_ADDRESS}"  
      GF_SMTP_FROM_NAME: "SpamShield Monitoring"
      GF_SMTP_STARTTLS_POLICY: "MandatoryStartTLS"

    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  mlflow_data:
  prometheus_data:
  grafana_data: