services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
        - mlflow_data:/mlruns


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
        - prometheus
    volumes:
      - grafana_data:/var/lib/grafana



volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  mlflow_data:
